#✅ Create unique namespace for your app
apiVersion: v1
kind: Namespace
metadata:
# ✅ Naming: k8s-STUDENTNAME or k8s-PAIRNAME
  name: k8s-raghadafghani
 # ✅ Labels for organization 
  labels:
    app.kubernetes.io/name: csv-processor
    app.kubernetes.io/instance: production
    environment: production
    owner: raghadafghani